


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html id="htmlId">
<head>
  <title>Coverage Report :: ListingErrorHandler</title>
  <style type="text/css">
    @import "../../.css/coverage.css";
  </style>
</head>

<body>
<div class="header"></div>

<div class="content">
<div class="breadCrumbs">
    [ <a href="../../index.html">all classes</a> ]
    [ <a href="../index.html">com.sun.org.apache.xml.internal.utils</a> ]
</div>

<h1>Coverage Summary for Class: ListingErrorHandler (com.sun.org.apache.xml.internal.utils)</h1>

<table class="coverageStats">
<tr>
  <th class="name">Class</th>
<th class="coverageStat 
">
  Class, %
</th>
<th class="coverageStat 
">
  Method, %
</th>
<th class="coverageStat 
">
  Line, %
</th>
</tr>
<tr>
  <td class="name">ListingErrorHandler</td>
<td class="coverageStat">
  <span class="percent">
    0%
  </span>
  <span class="absValue">
    (0/ 1)
  </span>
</td>
<td class="coverageStat">
  <span class="percent">
    0%
  </span>
  <span class="absValue">
    (0/ 17)
  </span>
</td>
<td class="coverageStat">
  <span class="percent">
    0%
  </span>
  <span class="absValue">
    (0/ 120)
  </span>
</td>
</tr>

</table>

<br/>
<br/>


<div class="sourceCode"><i>1</i>&nbsp;/*
<i>2</i>&nbsp; * Copyright (c) 2007, 2018, Oracle and/or its affiliates. All rights reserved.
<i>3</i>&nbsp; * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
<i>4</i>&nbsp; */
<i>5</i>&nbsp;/*
<i>6</i>&nbsp; * Licensed to the Apache Software Foundation (ASF) under one or more
<i>7</i>&nbsp; * contributor license agreements.  See the NOTICE file distributed with
<i>8</i>&nbsp; * this work for additional information regarding copyright ownership.
<i>9</i>&nbsp; * The ASF licenses this file to You under the Apache License, Version 2.0
<i>10</i>&nbsp; * (the &quot;License&quot;); you may not use this file except in compliance with
<i>11</i>&nbsp; * the License.  You may obtain a copy of the License at
<i>12</i>&nbsp; *
<i>13</i>&nbsp; *      http://www.apache.org/licenses/LICENSE-2.0
<i>14</i>&nbsp; *
<i>15</i>&nbsp; * Unless required by applicable law or agreed to in writing, software
<i>16</i>&nbsp; * distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
<i>17</i>&nbsp; * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
<i>18</i>&nbsp; * See the License for the specific language governing permissions and
<i>19</i>&nbsp; * limitations under the License.
<i>20</i>&nbsp; */
<i>21</i>&nbsp;
<i>22</i>&nbsp;package com.sun.org.apache.xml.internal.utils;
<i>23</i>&nbsp;
<i>24</i>&nbsp;import java.io.BufferedReader;
<i>25</i>&nbsp;import java.io.InputStream;
<i>26</i>&nbsp;import java.io.InputStreamReader;
<i>27</i>&nbsp;import java.io.PrintWriter;
<i>28</i>&nbsp;import java.net.URL;
<i>29</i>&nbsp;import java.net.URLConnection;
<i>30</i>&nbsp;
<i>31</i>&nbsp;import javax.xml.transform.ErrorListener;
<i>32</i>&nbsp;import javax.xml.transform.SourceLocator;
<i>33</i>&nbsp;import javax.xml.transform.TransformerException;
<i>34</i>&nbsp;
<i>35</i>&nbsp;import com.sun.org.apache.xml.internal.res.XMLErrorResources;
<i>36</i>&nbsp;import com.sun.org.apache.xml.internal.res.XMLMessages;
<i>37</i>&nbsp;
<i>38</i>&nbsp;import org.xml.sax.ErrorHandler;
<i>39</i>&nbsp;import org.xml.sax.SAXException;
<i>40</i>&nbsp;import org.xml.sax.SAXParseException;
<i>41</i>&nbsp;
<i>42</i>&nbsp;
<i>43</i>&nbsp;/**
<i>44</i>&nbsp; * Sample implementation of similar SAX ErrorHandler and JAXP ErrorListener.
<i>45</i>&nbsp; *
<i>46</i>&nbsp; * &lt;p&gt;This implementation is suitable for various use cases, and
<i>47</i>&nbsp; * provides some basic configuration API&#39;s as well to control
<i>48</i>&nbsp; * when we re-throw errors, etc.&lt;/p&gt;
<i>49</i>&nbsp; *
<i>50</i>&nbsp; * @author shane_curcuru@us.ibm.com
<i>51</i>&nbsp; * @xsl.usage general
<i>52</i>&nbsp; */
<i>53</i>&nbsp;public class ListingErrorHandler implements ErrorHandler, ErrorListener
<i>54</i>&nbsp;{
<i>55</i>&nbsp;    protected PrintWriter m_pw = null;
<i>56</i>&nbsp;
<b class="nc"><i>57</i>&nbsp;</b>
<i>58</i>&nbsp;    /**
<i>59</i>&nbsp;     * Constructor ListingErrorHandler; user-supplied PrintWriter.
<i>60</i>&nbsp;     */
<i>61</i>&nbsp;    public ListingErrorHandler(PrintWriter pw)
<i>62</i>&nbsp;    {
<i>63</i>&nbsp;        if (null == pw)
<b class="nc"><i>64</i>&nbsp;            throw new NullPointerException(XMLMessages.createXMLMessage(XMLErrorResources.ER_ERRORHANDLER_CREATED_WITH_NULL_PRINTWRITER, null));</b>
<b class="nc"><i>65</i>&nbsp;            // &quot;ListingErrorHandler created with null PrintWriter!&quot;);</b>
<b class="nc"><i>66</i>&nbsp;</b>
<i>67</i>&nbsp;        m_pw = pw;
<i>68</i>&nbsp;    }
<b class="nc"><i>69</i>&nbsp;</b>
<i>70</i>&nbsp;    /**
<i>71</i>&nbsp;     * Constructor ListingErrorHandler; uses System.err.
<i>72</i>&nbsp;     */
<i>73</i>&nbsp;    public ListingErrorHandler()
<i>74</i>&nbsp;    {
<i>75</i>&nbsp;        m_pw = new PrintWriter(System.err, true);
<b class="nc"><i>76</i>&nbsp;    }</b>
<b class="nc"><i>77</i>&nbsp;</b>
<i>78</i>&nbsp;
<i>79</i>&nbsp;    /* ======== Implement org.xml.sax.ErrorHandler ======== */
<i>80</i>&nbsp;    /**
<i>81</i>&nbsp;     * Receive notification of a warning.
<i>82</i>&nbsp;     *
<i>83</i>&nbsp;     * &lt;p&gt;SAX parsers will use this method to report conditions that
<i>84</i>&nbsp;     * are not errors or fatal errors as defined by the XML 1.0
<i>85</i>&nbsp;     * recommendation.  The default behaviour is to take no action.&lt;/p&gt;
<i>86</i>&nbsp;     *
<i>87</i>&nbsp;     * &lt;p&gt;The SAX parser must continue to provide normal parsing events
<i>88</i>&nbsp;     * after invoking this method: it should still be possible for the
<i>89</i>&nbsp;     * application to process the document through to the end.&lt;/p&gt;
<i>90</i>&nbsp;     *
<i>91</i>&nbsp;     * &lt;p&gt;Filters may use this method to report other, non-XML warnings
<i>92</i>&nbsp;     * as well.&lt;/p&gt;
<i>93</i>&nbsp;     *
<i>94</i>&nbsp;     * @param exception The warning information encapsulated in a
<i>95</i>&nbsp;     *                  SAX parse exception.
<i>96</i>&nbsp;     * @exception org.xml.sax.SAXException Any SAX exception, possibly
<i>97</i>&nbsp;     * wrapping another exception; only if setThrowOnWarning is true.
<i>98</i>&nbsp;     * @see org.xml.sax.SAXParseException
<i>99</i>&nbsp;     */
<i>100</i>&nbsp;    public void warning (SAXParseException exception)
<i>101</i>&nbsp;        throws SAXException
<i>102</i>&nbsp;    {
<i>103</i>&nbsp;        logExceptionLocation(m_pw, exception);
<i>104</i>&nbsp;        // Note: should we really call .toString() below, since
<b class="nc"><i>105</i>&nbsp;        //  sometimes the message is not properly set?</b>
<i>106</i>&nbsp;        m_pw.println(&quot;warning: &quot; + exception.getMessage());
<i>107</i>&nbsp;        m_pw.flush();
<b class="nc"><i>108</i>&nbsp;</b>
<b class="nc"><i>109</i>&nbsp;        if (getThrowOnWarning())</b>
<i>110</i>&nbsp;            throw exception;
<b class="nc"><i>111</i>&nbsp;    }</b>
<b class="nc"><i>112</i>&nbsp;</b>
<i>113</i>&nbsp;
<i>114</i>&nbsp;    /**
<i>115</i>&nbsp;     * Receive notification of a recoverable error.
<i>116</i>&nbsp;     *
<i>117</i>&nbsp;     * &lt;p&gt;This corresponds to the definition of &quot;error&quot; in section 1.2
<i>118</i>&nbsp;     * of the W3C XML 1.0 Recommendation.  For example, a validating
<i>119</i>&nbsp;     * parser would use this callback to report the violation of a
<i>120</i>&nbsp;     * validity constraint.  The default behaviour is to take no
<i>121</i>&nbsp;     * action.&lt;/p&gt;
<i>122</i>&nbsp;     *
<i>123</i>&nbsp;     * &lt;p&gt;The SAX parser must continue to provide normal parsing events
<i>124</i>&nbsp;     * after invoking this method: it should still be possible for the
<i>125</i>&nbsp;     * application to process the document through to the end.  If the
<i>126</i>&nbsp;     * application cannot do so, then the parser should report a fatal
<i>127</i>&nbsp;     * error even if the XML 1.0 recommendation does not require it to
<i>128</i>&nbsp;     * do so.&lt;/p&gt;
<i>129</i>&nbsp;     *
<i>130</i>&nbsp;     * &lt;p&gt;Filters may use this method to report other, non-XML errors
<i>131</i>&nbsp;     * as well.&lt;/p&gt;
<i>132</i>&nbsp;     *
<i>133</i>&nbsp;     * @param exception The error information encapsulated in a
<i>134</i>&nbsp;     *                  SAX parse exception.
<i>135</i>&nbsp;     * @exception org.xml.sax.SAXException Any SAX exception, possibly
<i>136</i>&nbsp;     * wrapping another exception; only if setThrowOnErroris true.
<i>137</i>&nbsp;     * @see org.xml.sax.SAXParseException
<i>138</i>&nbsp;     */
<i>139</i>&nbsp;    public void error (SAXParseException exception)
<i>140</i>&nbsp;        throws SAXException
<i>141</i>&nbsp;    {
<i>142</i>&nbsp;        logExceptionLocation(m_pw, exception);
<i>143</i>&nbsp;        m_pw.println(&quot;error: &quot; + exception.getMessage());
<b class="nc"><i>144</i>&nbsp;        m_pw.flush();</b>
<b class="nc"><i>145</i>&nbsp;</b>
<b class="nc"><i>146</i>&nbsp;        if (getThrowOnError())</b>
<i>147</i>&nbsp;            throw exception;
<b class="nc"><i>148</i>&nbsp;    }</b>
<b class="nc"><i>149</i>&nbsp;</b>
<i>150</i>&nbsp;
<i>151</i>&nbsp;    /**
<i>152</i>&nbsp;     * Receive notification of a non-recoverable error.
<i>153</i>&nbsp;     *
<i>154</i>&nbsp;     * &lt;p&gt;This corresponds to the definition of &quot;fatal error&quot; in
<i>155</i>&nbsp;     * section 1.2 of the W3C XML 1.0 Recommendation.  For example, a
<i>156</i>&nbsp;     * parser would use this callback to report the violation of a
<i>157</i>&nbsp;     * well-formedness constraint.&lt;/p&gt;
<i>158</i>&nbsp;     *
<i>159</i>&nbsp;     * &lt;p&gt;The application must assume that the document is unusable
<i>160</i>&nbsp;     * after the parser has invoked this method, and should continue
<i>161</i>&nbsp;     * (if at all) only for the sake of collecting addition error
<i>162</i>&nbsp;     * messages: in fact, SAX parsers are free to stop reporting any
<i>163</i>&nbsp;     * other events once this method has been invoked.&lt;/p&gt;
<i>164</i>&nbsp;     *
<i>165</i>&nbsp;     * @param exception The error information encapsulated in a
<i>166</i>&nbsp;     *                  SAX parse exception.
<i>167</i>&nbsp;     * @exception org.xml.sax.SAXException Any SAX exception, possibly
<i>168</i>&nbsp;     * wrapping another exception; only if setThrowOnFatalError is true.
<i>169</i>&nbsp;     * @see org.xml.sax.SAXParseException
<i>170</i>&nbsp;     */
<i>171</i>&nbsp;    public void fatalError (SAXParseException exception)
<i>172</i>&nbsp;        throws SAXException
<i>173</i>&nbsp;    {
<i>174</i>&nbsp;        logExceptionLocation(m_pw, exception);
<i>175</i>&nbsp;        m_pw.println(&quot;fatalError: &quot; + exception.getMessage());
<b class="nc"><i>176</i>&nbsp;        m_pw.flush();</b>
<b class="nc"><i>177</i>&nbsp;</b>
<b class="nc"><i>178</i>&nbsp;        if (getThrowOnFatalError())</b>
<i>179</i>&nbsp;            throw exception;
<b class="nc"><i>180</i>&nbsp;    }</b>
<b class="nc"><i>181</i>&nbsp;</b>
<i>182</i>&nbsp;
<i>183</i>&nbsp;    /* ======== Implement javax.xml.transform.ErrorListener ======== */
<i>184</i>&nbsp;
<i>185</i>&nbsp;    /**
<i>186</i>&nbsp;     * Receive notification of a warning.
<i>187</i>&nbsp;     *
<i>188</i>&nbsp;     * &lt;p&gt;{@link javax.xml.transform.Transformer} can use this method to report
<i>189</i>&nbsp;     * conditions that are not errors or fatal errors.  The default behaviour
<i>190</i>&nbsp;     * is to take no action.&lt;/p&gt;
<i>191</i>&nbsp;     *
<i>192</i>&nbsp;     * &lt;p&gt;After invoking this method, the Transformer must continue with
<i>193</i>&nbsp;     * the transformation. It should still be possible for the
<i>194</i>&nbsp;     * application to process the document through to the end.&lt;/p&gt;
<i>195</i>&nbsp;     *
<i>196</i>&nbsp;     * @param exception The warning information encapsulated in a
<i>197</i>&nbsp;     *                  transformer exception.
<i>198</i>&nbsp;     *
<i>199</i>&nbsp;     * @throws javax.xml.transform.TransformerException  only if
<i>200</i>&nbsp;     * setThrowOnWarning is true.
<i>201</i>&nbsp;     *
<i>202</i>&nbsp;     * @see javax.xml.transform.TransformerException
<i>203</i>&nbsp;     */
<i>204</i>&nbsp;    public void warning(TransformerException exception)
<i>205</i>&nbsp;        throws TransformerException
<i>206</i>&nbsp;    {
<i>207</i>&nbsp;        logExceptionLocation(m_pw, exception);
<i>208</i>&nbsp;        m_pw.println(&quot;warning: &quot; + exception.getMessage());
<b class="nc"><i>209</i>&nbsp;        m_pw.flush();</b>
<b class="nc"><i>210</i>&nbsp;</b>
<b class="nc"><i>211</i>&nbsp;        if (getThrowOnWarning())</b>
<i>212</i>&nbsp;            throw exception;
<b class="nc"><i>213</i>&nbsp;    }</b>
<b class="nc"><i>214</i>&nbsp;</b>
<i>215</i>&nbsp;    /**
<i>216</i>&nbsp;     * Receive notification of a recoverable error.
<i>217</i>&nbsp;     *
<i>218</i>&nbsp;     * &lt;p&gt;The transformer must continue to try and provide normal transformation
<i>219</i>&nbsp;     * after invoking this method.  It should still be possible for the
<i>220</i>&nbsp;     * application to process the document through to the end if no other errors
<i>221</i>&nbsp;     * are encountered.&lt;/p&gt;
<i>222</i>&nbsp;     *
<i>223</i>&nbsp;     * @param exception The error information encapsulated in a
<i>224</i>&nbsp;     *                  transformer exception.
<i>225</i>&nbsp;     *
<i>226</i>&nbsp;     * @throws javax.xml.transform.TransformerException  only if
<i>227</i>&nbsp;     * setThrowOnError is true.
<i>228</i>&nbsp;     *
<i>229</i>&nbsp;     * @see javax.xml.transform.TransformerException
<i>230</i>&nbsp;     */
<i>231</i>&nbsp;    public void error(TransformerException exception)
<i>232</i>&nbsp;        throws TransformerException
<i>233</i>&nbsp;    {
<i>234</i>&nbsp;        logExceptionLocation(m_pw, exception);
<i>235</i>&nbsp;        m_pw.println(&quot;error: &quot; + exception.getMessage());
<b class="nc"><i>236</i>&nbsp;        m_pw.flush();</b>
<b class="nc"><i>237</i>&nbsp;</b>
<b class="nc"><i>238</i>&nbsp;        if (getThrowOnError())</b>
<i>239</i>&nbsp;            throw exception;
<b class="nc"><i>240</i>&nbsp;    }</b>
<b class="nc"><i>241</i>&nbsp;</b>
<i>242</i>&nbsp;    /**
<i>243</i>&nbsp;     * Receive notification of a non-recoverable error.
<i>244</i>&nbsp;     *
<i>245</i>&nbsp;     * &lt;p&gt;The transformer must continue to try and provide normal transformation
<i>246</i>&nbsp;     * after invoking this method.  It should still be possible for the
<i>247</i>&nbsp;     * application to process the document through to the end if no other errors
<i>248</i>&nbsp;     * are encountered, but there is no guarantee that the output will be
<i>249</i>&nbsp;     * useable.&lt;/p&gt;
<i>250</i>&nbsp;     *
<i>251</i>&nbsp;     * @param exception The error information encapsulated in a
<i>252</i>&nbsp;     *                  transformer exception.
<i>253</i>&nbsp;     *
<i>254</i>&nbsp;     * @throws javax.xml.transform.TransformerException  only if
<i>255</i>&nbsp;     * setThrowOnError is true.
<i>256</i>&nbsp;     *
<i>257</i>&nbsp;     * @see javax.xml.transform.TransformerException
<i>258</i>&nbsp;     */
<i>259</i>&nbsp;    public void fatalError(TransformerException exception)
<i>260</i>&nbsp;        throws TransformerException
<i>261</i>&nbsp;    {
<i>262</i>&nbsp;        logExceptionLocation(m_pw, exception);
<i>263</i>&nbsp;        m_pw.println(&quot;error: &quot; + exception.getMessage());
<b class="nc"><i>264</i>&nbsp;        m_pw.flush();</b>
<b class="nc"><i>265</i>&nbsp;</b>
<b class="nc"><i>266</i>&nbsp;        if (getThrowOnError())</b>
<i>267</i>&nbsp;            throw exception;
<b class="nc"><i>268</i>&nbsp;    }</b>
<b class="nc"><i>269</i>&nbsp;</b>
<i>270</i>&nbsp;
<i>271</i>&nbsp;
<i>272</i>&nbsp;    /* ======== Implement worker methods ======== */
<i>273</i>&nbsp;
<i>274</i>&nbsp;
<i>275</i>&nbsp;    /**
<i>276</i>&nbsp;     * Print out location information about the exception.
<i>277</i>&nbsp;     *
<i>278</i>&nbsp;     * Cribbed from DefaultErrorHandler.printLocation()
<i>279</i>&nbsp;     * @param pw PrintWriter to send output to
<i>280</i>&nbsp;     * @param exception TransformerException or SAXParseException
<i>281</i>&nbsp;     * to log information about
<i>282</i>&nbsp;     */
<i>283</i>&nbsp;    public static void logExceptionLocation(PrintWriter pw, Throwable exception)
<i>284</i>&nbsp;    {
<i>285</i>&nbsp;        if (null == pw)
<i>286</i>&nbsp;            pw = new PrintWriter(System.err, true);
<b class="nc"><i>287</i>&nbsp;</b>
<b class="nc"><i>288</i>&nbsp;        SourceLocator locator = null;</b>
<i>289</i>&nbsp;        Throwable cause = exception;
<b class="nc"><i>290</i>&nbsp;</b>
<b class="nc"><i>291</i>&nbsp;        // Try to find the locator closest to the cause.</b>
<i>292</i>&nbsp;        do
<i>293</i>&nbsp;        {
<i>294</i>&nbsp;            // Find the current locator, if one present
<i>295</i>&nbsp;            if(cause instanceof SAXParseException)
<i>296</i>&nbsp;            {
<b class="nc"><i>297</i>&nbsp;                // A SAXSourceLocator is a Xalan helper class</b>
<i>298</i>&nbsp;                //  that implements both a SourceLocator and a SAX Locator
<i>299</i>&nbsp;                //@todo check that the new locator actually has
<i>300</i>&nbsp;                //  as much or more information as the
<i>301</i>&nbsp;                //  current one already does
<i>302</i>&nbsp;                locator = new SAXSourceLocator((SAXParseException)cause);
<i>303</i>&nbsp;            }
<b class="nc"><i>304</i>&nbsp;            else if (cause instanceof TransformerException)</b>
<i>305</i>&nbsp;            {
<b class="nc"><i>306</i>&nbsp;                SourceLocator causeLocator = ((TransformerException)cause).getLocator();</b>
<i>307</i>&nbsp;                if(null != causeLocator)
<b class="nc"><i>308</i>&nbsp;                {</b>
<b class="nc"><i>309</i>&nbsp;                    locator = causeLocator;</b>
<i>310</i>&nbsp;                }
<b class="nc"><i>311</i>&nbsp;            }</b>
<i>312</i>&nbsp;
<i>313</i>&nbsp;            // Then walk back down the chain of exceptions
<i>314</i>&nbsp;            if(cause instanceof TransformerException)
<i>315</i>&nbsp;                cause = ((TransformerException)cause).getCause();
<b class="nc"><i>316</i>&nbsp;            else if(cause instanceof WrappedRuntimeException)</b>
<b class="nc"><i>317</i>&nbsp;                cause = ((WrappedRuntimeException)cause).getException();</b>
<b class="nc"><i>318</i>&nbsp;            else if(cause instanceof SAXException)</b>
<b class="nc"><i>319</i>&nbsp;                cause = ((SAXException)cause).getException();</b>
<b class="nc"><i>320</i>&nbsp;            else</b>
<b class="nc"><i>321</i>&nbsp;                cause = null;</b>
<i>322</i>&nbsp;        }
<b class="nc"><i>323</i>&nbsp;        while(null != cause);</b>
<i>324</i>&nbsp;
<b class="nc"><i>325</i>&nbsp;        // Formatting note: mimic javac-like errors:</b>
<i>326</i>&nbsp;        //  path\filename:123: message-here
<i>327</i>&nbsp;        //  systemId:L=1;C=2: message-here
<i>328</i>&nbsp;        if(null != locator)
<i>329</i>&nbsp;        {
<b class="nc"><i>330</i>&nbsp;            String id = (locator.getPublicId() != locator.getPublicId())</b>
<i>331</i>&nbsp;                      ? locator.getPublicId()
<b class="nc"><i>332</i>&nbsp;                        : (null != locator.getSystemId())</b>
<b class="nc"><i>333</i>&nbsp;                          ? locator.getSystemId() : &quot;SystemId-Unknown&quot;;</b>
<b class="nc"><i>334</i>&nbsp;</b>
<b class="nc"><i>335</i>&nbsp;            pw.print(id + &quot;:Line=&quot; + locator.getLineNumber()</b>
<i>336</i>&nbsp;                             + &quot;;Column=&quot; + locator.getColumnNumber()+&quot;: &quot;);
<b class="nc"><i>337</i>&nbsp;            pw.println(&quot;exception:&quot; + exception.getMessage());</b>
<b class="nc"><i>338</i>&nbsp;            pw.println(&quot;root-cause:&quot;</b>
<b class="nc"><i>339</i>&nbsp;                       + ((null != cause) ? cause.getMessage() : &quot;null&quot;));</b>
<b class="nc"><i>340</i>&nbsp;            logSourceLine(pw, locator);</b>
<b class="nc"><i>341</i>&nbsp;        }</b>
<b class="nc"><i>342</i>&nbsp;        else</b>
<b class="nc"><i>343</i>&nbsp;        {</b>
<i>344</i>&nbsp;            pw.print(&quot;SystemId-Unknown:locator-unavailable: &quot;);
<i>345</i>&nbsp;            pw.println(&quot;exception:&quot; + exception.getMessage());
<b class="nc"><i>346</i>&nbsp;            pw.println(&quot;root-cause:&quot;</b>
<b class="nc"><i>347</i>&nbsp;                       + ((null != cause) ? cause.getMessage() : &quot;null&quot;));</b>
<b class="nc"><i>348</i>&nbsp;        }</b>
<b class="nc"><i>349</i>&nbsp;    }</b>
<i>350</i>&nbsp;
<i>351</i>&nbsp;
<i>352</i>&nbsp;    /**
<i>353</i>&nbsp;     * Print out the specific source line that caused the exception,
<i>354</i>&nbsp;     * if possible to load it.
<i>355</i>&nbsp;     *
<i>356</i>&nbsp;     * @param pw PrintWriter to send output to
<i>357</i>&nbsp;     * @param locator Xalan wrapper for either a JAXP or a SAX
<i>358</i>&nbsp;     * source location object
<i>359</i>&nbsp;     */
<i>360</i>&nbsp;    public static void logSourceLine(PrintWriter pw, SourceLocator locator)
<i>361</i>&nbsp;    {
<i>362</i>&nbsp;        if (null == locator)
<i>363</i>&nbsp;            return;
<b class="nc"><i>364</i>&nbsp;</b>
<i>365</i>&nbsp;        if (null == pw)
<i>366</i>&nbsp;            pw = new PrintWriter(System.err, true);
<b class="nc"><i>367</i>&nbsp;</b>
<b class="nc"><i>368</i>&nbsp;        String url = locator.getSystemId();</b>
<i>369</i>&nbsp;        // Bail immediately if we get SystemId-Unknown
<b class="nc"><i>370</i>&nbsp;        //@todo future improvement: attempt to get resource</b>
<i>371</i>&nbsp;        //  from a publicId if possible
<i>372</i>&nbsp;        if (null == url)
<i>373</i>&nbsp;        {
<b class="nc"><i>374</i>&nbsp;            pw.println(&quot;line: (No systemId; cannot read file)&quot;);</b>
<i>375</i>&nbsp;            pw.println();
<b class="nc"><i>376</i>&nbsp;            return;</b>
<b class="nc"><i>377</i>&nbsp;        }</b>
<i>378</i>&nbsp;
<i>379</i>&nbsp;        //@todo attempt to get DOM backpointer or other ids
<i>380</i>&nbsp;
<i>381</i>&nbsp;        try
<i>382</i>&nbsp;        {
<i>383</i>&nbsp;            int line = locator.getLineNumber();
<i>384</i>&nbsp;            int column = locator.getColumnNumber();
<b class="nc"><i>385</i>&nbsp;            pw.println(&quot;line: &quot; + getSourceLine(url, line));</b>
<b class="nc"><i>386</i>&nbsp;            StringBuffer buf = new StringBuffer(&quot;line: &quot;);</b>
<b class="nc"><i>387</i>&nbsp;            for (int i = 1; i &lt; column; i++)</b>
<b class="nc"><i>388</i>&nbsp;            {</b>
<b class="nc"><i>389</i>&nbsp;                buf.append(&#39; &#39;);</b>
<i>390</i>&nbsp;            }
<b class="nc"><i>391</i>&nbsp;            buf.append(&#39;^&#39;);</b>
<i>392</i>&nbsp;            pw.println(buf.toString());
<b class="nc"><i>393</i>&nbsp;        }</b>
<b class="nc"><i>394</i>&nbsp;        catch (Exception e)</b>
<i>395</i>&nbsp;        {
<b class="nc"><i>396</i>&nbsp;            pw.println(&quot;line: logSourceLine unavailable due to: &quot; + e.getMessage());</b>
<i>397</i>&nbsp;            pw.println();
<b class="nc"><i>398</i>&nbsp;        }</b>
<b class="nc"><i>399</i>&nbsp;    }</b>
<b class="nc"><i>400</i>&nbsp;</b>
<i>401</i>&nbsp;
<i>402</i>&nbsp;    /**
<i>403</i>&nbsp;     * Return the specific source line that caused the exception,
<i>404</i>&nbsp;     * if possible to load it; allow exceptions to be thrown.
<i>405</i>&nbsp;     *
<i>406</i>&nbsp;     * @author shane_curcuru@us.ibm.com
<i>407</i>&nbsp;     */
<i>408</i>&nbsp;    protected static String getSourceLine(String sourceUrl, int lineNum)
<i>409</i>&nbsp;            throws Exception
<i>410</i>&nbsp;    {
<i>411</i>&nbsp;        URL url = null;
<i>412</i>&nbsp;        // Get a URL from the sourceUrl
<b class="nc"><i>413</i>&nbsp;        try</b>
<i>414</i>&nbsp;        {
<i>415</i>&nbsp;            // Try to get a URL from it as-is
<i>416</i>&nbsp;            url = new URL(sourceUrl);
<i>417</i>&nbsp;        }
<b class="nc"><i>418</i>&nbsp;        catch (java.net.MalformedURLException mue)</b>
<i>419</i>&nbsp;        {
<b class="nc"><i>420</i>&nbsp;            int indexOfColon = sourceUrl.indexOf(&#39;:&#39;);</b>
<i>421</i>&nbsp;            int indexOfSlash = sourceUrl.indexOf(&#39;/&#39;);
<b class="nc"><i>422</i>&nbsp;</b>
<b class="nc"><i>423</i>&nbsp;            if ((indexOfColon != -1)</b>
<i>424</i>&nbsp;                &amp;&amp; (indexOfSlash != -1)
<b class="nc"><i>425</i>&nbsp;                &amp;&amp; (indexOfColon &lt; indexOfSlash))</b>
<i>426</i>&nbsp;            {
<i>427</i>&nbsp;                // The url is already absolute, but we could not get
<i>428</i>&nbsp;                //  the system to form it, so bail
<i>429</i>&nbsp;                throw mue;
<i>430</i>&nbsp;            }
<b class="nc"><i>431</i>&nbsp;            else</b>
<i>432</i>&nbsp;            {
<i>433</i>&nbsp;                // The url is relative, so attempt to get absolute
<i>434</i>&nbsp;                url = new URL(SystemIDResolver.getAbsoluteURI(sourceUrl));
<i>435</i>&nbsp;                // If this fails, allow the exception to propagate
<b class="nc"><i>436</i>&nbsp;            }</b>
<i>437</i>&nbsp;        }
<i>438</i>&nbsp;
<b class="nc"><i>439</i>&nbsp;        String line = null;</b>
<i>440</i>&nbsp;        InputStream is = null;
<b class="nc"><i>441</i>&nbsp;        BufferedReader br = null;</b>
<b class="nc"><i>442</i>&nbsp;        try</b>
<b class="nc"><i>443</i>&nbsp;        {</b>
<i>444</i>&nbsp;            // Open the URL and read to our specified line
<i>445</i>&nbsp;            URLConnection uc = url.openConnection();
<i>446</i>&nbsp;            is = uc.getInputStream();
<b class="nc"><i>447</i>&nbsp;            br = new BufferedReader(new InputStreamReader(is));</b>
<b class="nc"><i>448</i>&nbsp;</b>
<b class="nc"><i>449</i>&nbsp;            // Not the most efficient way, but it works</b>
<i>450</i>&nbsp;            // (Feel free to patch to seek to the appropriate line)
<i>451</i>&nbsp;            for (int i = 1; i &lt;= lineNum; i++)
<i>452</i>&nbsp;            {
<b class="nc"><i>453</i>&nbsp;                line = br.readLine();</b>
<i>454</i>&nbsp;            }
<b class="nc"><i>455</i>&nbsp;</b>
<i>456</i>&nbsp;        }
<i>457</i>&nbsp;        // Allow exceptions to propagate from here, but ensure
<i>458</i>&nbsp;        //  streams are closed!
<i>459</i>&nbsp;        finally
<i>460</i>&nbsp;        {
<i>461</i>&nbsp;            br.close();
<i>462</i>&nbsp;            is.close();
<b class="nc"><i>463</i>&nbsp;        }</b>
<b class="nc"><i>464</i>&nbsp;</b>
<b class="nc"><i>465</i>&nbsp;        // Return whatever we found</b>
<i>466</i>&nbsp;        return line;
<i>467</i>&nbsp;    }
<b class="nc"><i>468</i>&nbsp;</b>
<i>469</i>&nbsp;
<i>470</i>&nbsp;    /* ======== Implement settable properties ======== */
<i>471</i>&nbsp;
<i>472</i>&nbsp;    /**
<i>473</i>&nbsp;     * User-settable behavior: when to re-throw exceptions.
<i>474</i>&nbsp;     *
<i>475</i>&nbsp;     * &lt;p&gt;This allows per-instance configuration of
<i>476</i>&nbsp;     * ListingErrorHandlers.  You can ask us to either throw
<i>477</i>&nbsp;     * an exception when we&#39;re called for various warning /
<i>478</i>&nbsp;     * error / fatalErrors, or simply log them and continue.&lt;/p&gt;
<i>479</i>&nbsp;     *
<i>480</i>&nbsp;     * @param b if we should throw an exception on warnings
<i>481</i>&nbsp;     */
<i>482</i>&nbsp;    public void setThrowOnWarning(boolean b)
<i>483</i>&nbsp;    {
<i>484</i>&nbsp;        throwOnWarning = b;
<i>485</i>&nbsp;    }
<b class="nc"><i>486</i>&nbsp;</b>
<i>487</i>&nbsp;    /**
<i>488</i>&nbsp;     * User-settable behavior: when to re-throw exceptions.
<i>489</i>&nbsp;     *
<i>490</i>&nbsp;     * @return if we throw an exception on warnings
<i>491</i>&nbsp;     */
<i>492</i>&nbsp;    public boolean getThrowOnWarning()
<i>493</i>&nbsp;    {
<i>494</i>&nbsp;        return throwOnWarning;
<i>495</i>&nbsp;    }
<b class="nc"><i>496</i>&nbsp;</b>
<i>497</i>&nbsp;    /** If we should throw exception on warnings; default:false.  */
<i>498</i>&nbsp;    protected boolean throwOnWarning = false;
<i>499</i>&nbsp;
<b class="nc"><i>500</i>&nbsp;</b>
<i>501</i>&nbsp;    /**
<i>502</i>&nbsp;     * User-settable behavior: when to re-throw exceptions.
<i>503</i>&nbsp;     *
<i>504</i>&nbsp;     * &lt;p&gt;This allows per-instance configuration of
<i>505</i>&nbsp;     * ListingErrorHandlers.  You can ask us to either throw
<i>506</i>&nbsp;     * an exception when we&#39;re called for various warning /
<i>507</i>&nbsp;     * error / fatalErrors, or simply log them and continue.&lt;/p&gt;
<i>508</i>&nbsp;     *
<i>509</i>&nbsp;     * &lt;p&gt;Note that the behavior of many parsers/transformers
<i>510</i>&nbsp;     * after an error is not necessarily defined!&lt;/p&gt;
<i>511</i>&nbsp;     *
<i>512</i>&nbsp;     * @param b if we should throw an exception on errors
<i>513</i>&nbsp;     */
<i>514</i>&nbsp;    public void setThrowOnError(boolean b)
<i>515</i>&nbsp;    {
<i>516</i>&nbsp;        throwOnError = b;
<i>517</i>&nbsp;    }
<b class="nc"><i>518</i>&nbsp;</b>
<i>519</i>&nbsp;    /**
<i>520</i>&nbsp;     * User-settable behavior: when to re-throw exceptions.
<i>521</i>&nbsp;     *
<i>522</i>&nbsp;     * @return if we throw an exception on errors
<i>523</i>&nbsp;     */
<i>524</i>&nbsp;    public boolean getThrowOnError()
<i>525</i>&nbsp;    {
<i>526</i>&nbsp;        return throwOnError;
<i>527</i>&nbsp;    }
<b class="nc"><i>528</i>&nbsp;</b>
<i>529</i>&nbsp;    /** If we should throw exception on errors; default:true.  */
<i>530</i>&nbsp;    protected boolean throwOnError = true;
<i>531</i>&nbsp;
<b class="nc"><i>532</i>&nbsp;</b>
<i>533</i>&nbsp;    /**
<i>534</i>&nbsp;     * User-settable behavior: when to re-throw exceptions.
<i>535</i>&nbsp;     *
<i>536</i>&nbsp;     * &lt;p&gt;This allows per-instance configuration of
<i>537</i>&nbsp;     * ListingErrorHandlers.  You can ask us to either throw
<i>538</i>&nbsp;     * an exception when we&#39;re called for various warning /
<i>539</i>&nbsp;     * error / fatalErrors, or simply log them and continue.&lt;/p&gt;
<i>540</i>&nbsp;     *
<i>541</i>&nbsp;     * &lt;p&gt;Note that the behavior of many parsers/transformers
<i>542</i>&nbsp;     * after a fatalError is not necessarily defined, most
<i>543</i>&nbsp;     * products will probably barf if you continue.&lt;/p&gt;
<i>544</i>&nbsp;     *
<i>545</i>&nbsp;     * @param b if we should throw an exception on fatalErrors
<i>546</i>&nbsp;     */
<i>547</i>&nbsp;    public void setThrowOnFatalError(boolean b)
<i>548</i>&nbsp;    {
<i>549</i>&nbsp;        throwOnFatalError = b;
<i>550</i>&nbsp;    }
<b class="nc"><i>551</i>&nbsp;</b>
<i>552</i>&nbsp;    /**
<i>553</i>&nbsp;     * User-settable behavior: when to re-throw exceptions.
<i>554</i>&nbsp;     *
<i>555</i>&nbsp;     * @return if we throw an exception on fatalErrors
<i>556</i>&nbsp;     */
<i>557</i>&nbsp;    public boolean getThrowOnFatalError()
<i>558</i>&nbsp;    {
<i>559</i>&nbsp;        return throwOnFatalError;
<i>560</i>&nbsp;    }
<b class="nc"><i>561</i>&nbsp;</b>
<i>562</i>&nbsp;    /** If we should throw exception on fatalErrors; default:true.  */
<i>563</i>&nbsp;    protected boolean throwOnFatalError = true;
<i>564</i>&nbsp;
<b class="nc"><i>565</i>&nbsp;}</b>
</div>
</div>

<div class="footer">
    
    <div style="float:right;">generated on 2018-11-19 23:15</div>
</div>
</body>
</html>
